### ISSUE TITLE
npm ERR! code ELIFECYCLE

### ISSUE THREAD

**Issue by Sadanandgadwal** [Anantm007/Dev-Bookstore#7]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ecommerce@1.0.0 start: `node app`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ecommerce@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
![Screenshot (10)](https://user-images.githubusercontent.com/83832977/117551342-0958d680-b063-11eb-8d28-b49c5dfb7ef4.png)

**Comment by Anantm007** [comment]
@yesg07 please show the complete error. and did you set up a .env file?

**Comment by Sadanandgadwal** [comment]
I have done

**Comment by Anantm007** [comment]
Please scroll up and show the complete error

**Comment by yesg07** [comment]
Still I am error

**Comment by Sadanandgadwal** [comment]
[0] 
[0] > ecommerce@1.0.0 server C:\Users\sadan\dev-bookstore-master
[0] > nodemon app
[0] 
[1] 
[1] > ecommerce@1.0.0 client C:\Users\sadan\dev-bookstore-master
[1] > npm start --prefix client
[1] 
[0] [nodemon] 1.19.4
[0] [nodemon] to restart at any time, enter `rs`
[0] [nodemon] watching dir(s): *.*
[0] [nodemon] watching extensions: js,mjs,json
[0] [nodemon] starting `node app.js`
[0] C:\Users\sadan\dev-bookstore-master\node_modules\express-jwt\lib\index.js:20
[0]   if (!options || !options.secret) throw new Error('secret should be set');
[0]                                    ^
[0] 
[0] Error: secret should be set
[0]     at module.exports (C:\Users\sadan\dev-bookstore-master\node_modules\express-jwt\lib\index.js:20:42)
[0]     at Object.<anonymous> (C:\Users\sadan\dev-bookstore-master\controllers\auth.js:106:25)
[0]     at Module._compile (internal/modules/cjs/loader.js:1063:30)
[0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
[0]     at Module.load (internal/modules/cjs/loader.js:928:32)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
[0]     at Module.require (internal/modules/cjs/loader.js:952:19)
[0]     at require (internal/modules/cjs/helpers.js:88:18)
[0]     at Object.<anonymous> (C:\Users\sadan\dev-bookstore-master\routes\auth.js:6:35)
[0]     at Module._compile (internal/modules/cjs/loader.js:1063:30)
[0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
[0]     at Module.load (internal/modules/cjs/loader.js:928:32)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
[0]     at Module.require (internal/modules/cjs/loader.js:952:19)
[0]     at require (internal/modules/cjs/helpers.js:88:18)
[0]     at Object.<anonymous> (C:\Users\sadan\dev-bookstore-master\app.js:19:20)
[0] [nodemon] app crashed - waiting for file changes before starting...
[1]
[1] > client@0.1.0 start C:\Users\sadan\dev-bookstore-master\client
[1] > PORT=3010 react-scripts start
[1]
[1] 'PORT' is not recognized as an internal or external command,
[1] operable program or batch file.
[1] npm ERR! code ELIFECYCLE
npm ERR! errno 1
[1] npm ERR! client@0.1.0 start: `PORT=3010 react-scripts start`
[1] npm ERR! Exit status 1
[1] npm ERR!
npm ERR! Failed at the client@0.1.0 start script.
[1] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[1]
[1] npm ERR! A complete log of this run can be found in:
[1] npm ERR!     C:\Users\sadan\AppData\Roaming\npm-cache\_logs\2021-05-08T20_46_16_002Z-debug.log
[1] npm ERR! code ELIFECYCLE
npm ERR! errno 1
[1] npm ERR! ecommerce@1.0.0 client: `npm start --prefix client`
[1] npm ERR! Exit status 1
[1] npm ERR!
[1] npm ERR! Failed at the ecommerce@1.0.0 client script.
[1] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[1]
[1] npm ERR! A complete log of this run can be found in:
[1] npm ERR!     C:\Users\sadan\AppData\Roaming\npm-cache\_logs\2021-05-08T20_46_16_224Z-debug.log
[1] npm run client exited with code 1
![Screenshot (15)](https://user-images.githubusercontent.com/83832977/117553089-ff3bd580-b06c-11eb-8346-ab68244ca25e.png)
![Screenshot (16)](https://user-images.githubusercontent.com/83832977/117553094-02cf5c80-b06d-11eb-9b7d-69c6ddb00df9.png)

**Comment by Anantm007** [comment]
@yesg07 please remind me in a couple of hours. Will see after office work.
